import express from 'express';
import axios from 'axios';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import querystring from 'querystring';
import formidable from 'formidable'; // To handle file uploads
import fs from 'fs';
import { Readable } from 'stream';
import 'dotenv/config';

const app = express();
const port = 8888;
const stateKey = 'spotify_auth_state';

const client_id = process.env.SPOTIFY_CLIENT_ID;
const client_secret = process.env.SPOTIFY_CLIENT_SECRET;
const redirect_uri = process.env.REDIRECT_URI;
const frontend_uri = process.env.FRONTEND_URI;

app.use(cors({
    origin: frontend_uri,
    credentials: true
}))
.use(cookieParser());

const generateRandomString = (length: number): string => {
    let text = '';
    const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    for (let i = 0; i < length; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
};

app.post('/upload-for-nft', async (req, res) => {
    try {
        // 1. Initialize Pinata SDK with your keys (from .env)
        const pinata = new PinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_SECRET_KEY);

        // You would send the image generated by html2canvas here
        // For simplicity, this example assumes the image data is sent in the body
        // A robust solution would use multipart/form-data
        const imageBuffer = Buffer.from(req.body.imageData, 'base64');
        const imageStream = Readable.from(imageBuffer);

        // 2. Upload the image to IPFS
        const imageResult = await pinata.pinFileToIPFS(imageStream, {
            pinataMetadata: { name: 'receipt.png' },
        });
        const imageIpfsUrl = `https://gateway.pinata.cloud/ipfs/${imageResult.IpfsHash}`;

        // 3. Create the metadata JSON
        const metadata = {
            name: `Spotify Receipt for ${req.body.userName}`,
            description: `A snapshot of top tracks from ${req.body.timeRange}.`,
            image: imageIpfsUrl,
            attributes: req.body.tracks // Pass tracks as attributes
        };

        // 4. Upload the metadata JSON to IPFS
        const metadataResult = await pinata.pinJSONToIPFS(metadata, {
            pinataMetadata: { name: 'receipt-metadata.json' },
        });
        const metadataIpfsUrl = `https://gateway.pinata.cloud/ipfs/${metadataResult.IpfsHash}`;

        // 5. Send the metadata URL back to the frontend
        res.json({ tokenURI: metadataIpfsUrl });

    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to upload to IPFS' });
    }
});

app.get('/login', (req, res) => {
    const state = generateRandomString(16);
    res.cookie(stateKey, state);
    const scope = 'user-top-read';
    res.redirect('https://accounts.spotify.com/authorize?' +
        querystring.stringify({
            response_type: 'code',
            client_id: client_id,
            scope: scope,
            redirect_uri: redirect_uri,
            state: state
        }));
});

// Add this new route to your src/server.ts file

app.get('/refresh_token', async (req, res) => {
    const { refresh_token } = req.query;

    if (!refresh_token) {
        return res.status(400).json({ error: 'Refresh token is missing' });
    }

    try {
        const response = await axios({
            method: 'post',
            url: 'https://accounts.spotify.com/api/token',
            data: querystring.stringify({
                grant_type: 'refresh_token',
                refresh_token: refresh_token as string,
            }),
            headers: {
                'content-type': 'application/x-www-form-urlencoded',
                'Authorization': `Basic ${Buffer.from(`${client_id}:${client_secret}`).toString('base64')}`,
            },
        });

        res.json({
            access_token: response.data.access_token,
        });

    } catch (error) {
        res.status(400).json({ error: 'Invalid refresh token' });
    }
});

app.get('/callback', async (req, res) => {
    const code = req.query.code || null;
    const state = req.query.state || null;
    const storedState = req.cookies ? req.cookies[stateKey] : null;

    if (state === null || state !== storedState) {
        res.redirect(`${frontend_uri}/#${querystring.stringify({ error: 'state_mismatch' })}`);
    } else {
        res.clearCookie(stateKey);
        try {
            const response = await axios({
                method: 'post',
                url: 'https://accounts.spotify.com/api/token',
                data: querystring.stringify({
                    grant_type: 'authorization_code',
                    code: code as string,
                    redirect_uri: redirect_uri
                }),
                headers: {
                    'content-type': 'application/x-www-form-urlencoded',
                    'Authorization': `Basic ${Buffer.from(`${client_id}:${client_secret}`).toString('base64')}`,
                },
            });

            const { access_token, refresh_token } = response.data;
            res.redirect(`${frontend_uri}/?access_token=${access_token}&refresh_token=${refresh_token}`);

        } catch (error) {
            res.redirect(`${frontend_uri}/#${querystring.stringify({ error: 'invalid_token' })}`);
        }
    }
});

app.listen(port, () => {
    console.log(`Backend server is listening at http://localhost:${port}`);
});
